[package]
name = "wascc-host"
version = "0.6.1"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"
homepage = "https://wascc.dev"
repository = "https://github.com/wascc/wascc-host"
description = "WebAssembly Secure Capabilities Connector (waSCC) Host Runtime"
license = "Apache-2.0"
documentation = "https://docs.rs/wascc-host"
readme = "README.md"
keywords = ["webassembly", "wasm", "wasi", "wascc", "wapc"]
categories = ["wasm", "api-bindings","command-line-utilities"]
exclude = ["examples/.assets"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
libloading = "0.5.2"
crossbeam-channel = "0.4.2"
crossbeam = "0.7.3"
crossbeam-utils = "^0.7.0"
wapc = "0.5.0"
wascc-codec = "0.6.0"
wascap = "0.4.5"
log = "0.4.8"
lazy_static = "1.4.0"
rand = "0.7.3"
env_logger = "0.7.1"

uuid = { version = "0.8", features = ["serde", "v4"] }

gantryclient = { version = "0.0.4", optional = true }

serde = { version = "1.0", features = ["derive"], optional = true }
serde_yaml = { version = "0.8.11", optional = true }
serde_json = { version = "1.0", optional = true }
envmnt = { version = "0.8.1", optional = true }

structopt = { version = "0.3.12", optional = true }

[features]
default = []
manifest = ["serde", "serde_yaml", "serde_json", "envmnt"]
bin = ["structopt"]
gantry = ["gantryclient"]

[[bin]]
name = "wascc-host"
path = "src/bin.rs"
required-features = ["manifest", "bin"]
