[package]
name = "wascc-host"
version = "0.3.2"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"
homepage = "https://wascc.dev"
description = "WebAssembly Secure Capabilities Connector (waSCC) Host Runtime"
license = "Apache-2.0"
documentation = "https://docs.rs/wascc-host"
readme = "README.md"
keywords = ["webassembly", "wasm", "wasi", "wascc", "wapc"]
categories = ["wasm", "api-bindings","command-line-utilities"]
exclude = ["examples/.assets"]

[badges]
maintenance = { status = "actively-developed" }
travis-ci = { repository = "wascc/wascc-host", branch = "master" }


[dependencies]
libloading = "0.5.2"
crossbeam-channel = "0.4.2"
crossbeam = "0.7.3"
crossbeam-utils = "^0.7.0"
wapc = "0.2.1"
wascc-codec = "0.4.1"
wascap = "0.4.0"
prost = "0.6.1"
log = "0.4.8"
env_logger = "0.7.1"
lazy_static = "1.4.0"
gantryclient = { path = "../gantry/client/gantryclient"}
rand = "0.7.3"
uuid = { version = "0.8", features = ["serde", "v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.11"
serde_json = "1.0"

quicli = "0.4"
structopt = "0.3.9"