name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build all features
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run fmt
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose --all-features    
  
  test:
    name: Test feature matrix
    runs-on: ubuntu-latest

    services:
      names:
        image: nats
        ports:
          - 6222:6222
          - 4222:4222
          - 8222:8222

    steps:
      - uses: actions/checkout@v2       
      - name: Run tests Gantry+Manifest
        run: cargo test --verbose --features "manifest gantry bin"      
      - name: Run tests (manifest only)
        run: cargo test --verbose --features "manifest"      
      - name: Run tests (gantry only)
        run: cargo test --verbose --features "gantry"      
      - name: Run tests (lattice mode)
        run: cargo test --verbose --features "manifest lattice"
        env:
          LATTICE_HOST: 0.0.0.0
          LATTICE_RPC_TIMEOUT_MILLIS: 100